services:
  maerbooru:
    container_name: maerbooru
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6364:8080
    environment:
      - LEPTOS_SITE_ADDR=0.0.0.0:8080
    volumes:
      - ./uploads:/app/uploads
