services:
  maerbooru:
    container_name: maerbooru
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6364:8000
    environment:
      - LEPTOS_SITE_ADDR=0.0.0.0:8000
      - SURREALDB_USER=root
      - SURREALDB_PASS=root
      - SURREAL_URL=db:8080
    volumes:
      - ./uploads:/app/uploads
    networks:
      internal_network:
        aliases:
          - maerbooru
    depends_on:
      - db
  db:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    volumes:
      - ./db:/db
    command: start --user root --pass root surrealkv:///db
    networks:
      internal_network:
        aliases:
          - surrealdb

networks:
  internal_network:
